#!/bin/bash

if [ ! -f keys/authorized_keys ]; then
  echo
  cp ~/.ssh/id_rsa.pub ./keys/authorized_keys
  exit 1
fi

if [ ! -f keys/authorized_keys ]; then
  echo
  echo "Unable to find SSH public key at ~/.ssh/id_rsa.pub to seed ./keys/authorized_keys!"
  echo "Please make sure you have a public key available for passwordless SSH installation into the node."
  exit 1
fi

packer build cluster-node.json