  - name: ensure the iscs-manifests folder exists in the cluster package
    local_action:
      module: shell
      _raw_params: mkdir -p ../clusters/{{ cluster_pkg_folder }}/iscsi-manifests
    become: false
    when: targetd_server is defined 

  - name: read VM Node Initiator value for storage class 
    shell: CODE=`cat /etc/iscsi/initiatorname.iscsi` && echo ${CODE//InitiatorName=/}
    register: vm_initiator_code
    when: targetd_server is defined and cluster_type != "ubuntu-k8s"
  
  - debug: msg="{{ vm_initiator_code.stdout }}"
    when: targetd_server is defined and cluster_type != "ubuntu-k8s"

  - name: assign initiator fact 
    set_fact:
      initiator_name: "{{ vm_initiator_code.stdout }}"
    when: targetd_server is defined and cluster_type != "ubuntu-k8s"

  - name: read node iscsi initiator value in Ubuntu OS
    shell: cat /etc/iscsi/initiatorname.iscsi | grep InitiatorName= | sed 's/^InitiatorName=//'
    register: vm_initiator_code
    when: targetd_server is defined and cluster_type == "ubuntu-k8s"

  - debug: msg="{{ vm_initiator_code.stdout }}"
    when: targetd_server is defined and cluster_type == "ubuntu-k8s"

  - name: assign initiator fact 
    set_fact:
      initiator_name: "{{ vm_initiator_code.stdout }}"
    when: targetd_server is defined and cluster_type == "ubuntu-k8s"

  - debug: msg="{{ initiator_name }}"
    when: targetd_server is defined 
  
  - name: assign default storage class name
    set_fact:
      targetd_server_storage_class: "iscsi-targetd-vg-targetd"
    when: targetd_server is defined and targetd_server_storage_class is undefined

  - name: generate the iSCSI provisioner, roles and storage class manifest
    local_action:
      module: template
      src: templates/k8s-iscsi-manifests.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/iscsi-manifests/iscsi.yml
    become: false
    when: targetd_server is defined

  - name: generate the iSCSI benchmark manifest
    local_action:
      module: template
      src: templates/k8s-iscsi-bench-pvc-yml.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/iscsi-manifests/iscsi-bench-pvc.yml
    become: false
    run_once: true
    when: targetd_server is defined 

  - name: generate the iSCSI benchmark manifest
    local_action:
      module: template
      src: templates/k8s-iscsi-bench-job-yml.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/iscsi-manifests/iscsi-bench-job.yml
    become: false
    run_once: true
    when: targetd_server is defined 

  - name: generate the iSCSI provisioner secret script
    local_action:
      module: template
      src: templates/k8s-iscsi-secret.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/iscsi-manifests/iscsi-secret.sh
      mode: 0766
    become: false    
    when: targetd_server is defined 


